apiVersion: v1
kind: Service
metadata:
  name: playground-github-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: playground-github
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
